before_script:
    - 'git submodule update --init'

stages:
  - build
  - test

run_build:
  stage: build
  script:
    - './build.sh'
  tags:
    - venus linux

run_tests:
  stage: test
  script:
    - './test.sh'
  tags:
    - linux-qt5.5
